[package]
name = "flash_executor"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
# Anchor CLI will pass --features idl-build when extracting the IDL
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []

[dependencies]
anchor-lang = "0.31.1"
anchor-spl  = "0.31.1"
spl-token-2022 = "6.0.0"
