module.exports={
  RAYDIUM_ROUTER:"DRaybByLpbUL57LJARs3j8BitTxVfzBg351EaMr5UTCd",
  RAYDIUM_CPMM:"DRaycpLY18LhpbydsBWbVJtxpNv9oXPgjRSfpF2bWpYb",
  RAYDIUM_CLMM:"DRayAUgENGQBKVaX8owNhgzkEDyoHTGVEGHVJT1E9pfH"
};
